[build]
# No build command - files are pre-built by GitHub Actions
command = ""
# Publish the root directory which contains pre-built files
publish = "."

# Environment variables
[build.environment]
NODE_ENV = "production"

# Headers for WASM and security
[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Opener-Policy = "same-origin"
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"

# WASM MIME type with no caching and ETag control
[[headers]]
for = "*.wasm"
[headers.values]
Content-Type = "application/wasm"
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"
ETag = ""
Last-Modified = ""

# JavaScript files with no caching and ETag control
[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"
ETag = ""
Last-Modified = ""

# HTML files with no caching and ETag control
[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"
ETag = ""
Last-Modified = ""

# Production deployment from deploy branch
[context.production]
command = ""
publish = "."

# Deploy previews
[context.deploy-preview]
command = ""
publish = "."

# Branch deploys
[context.branch-deploy]
command = ""
publish = "."

# SPA fallback for routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
