[build]
# No build command - files are pre-built by GitHub Actions
# This configuration assumes Netlify is connected to the 'deploy' branch
# which contains the pre-built game files
publish = "."
command = ""
# No ignore needed - always deploy from deploy branch

# Skip build processing since files are already built
[build.processing]
skip_processing = true

# Headers for WASM and security
[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Opener-Policy = "same-origin"
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# WASM MIME type - reduced caching for cache-busted files
[[headers]]
for = "*.wasm"
[headers.values]
Content-Type = "application/wasm"
Cache-Control = "public, max-age=3600"

# JavaScript files caching - reduced for cache-busted files
[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=3600"

# HTML files - no caching to ensure latest references
[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# Production deployment (from deploy branch)
[context.production]
publish = "."
command = ""

# Branch deploys (only from deploy branch)
[context.deploy-preview]
publish = "."
command = ""

# Deploy previews for the deploy branch
[context.branch-deploy]
publish = "."
command = ""

# Environment variables for different contexts
[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
NODE_ENV = "preview"
