[build]
# Build command to run the same script as local
command = "./build-web.sh"
# Publish the dist directory created by build script
publish = "dist"

# Environment variables
[build.environment]
NODE_ENV = "production"

# Headers for WASM and security
[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Opener-Policy = "same-origin"
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"

# WASM MIME type with no caching
[[headers]]
for = "*.wasm"
[headers.values]
Content-Type = "application/wasm"
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# JavaScript files with no caching
[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# HTML files with no caching
[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# Production deployment from deploy branch
[context.production]
command = "./build-web.sh"
publish = "dist"

# Deploy previews
[context.deploy-preview]
command = "./build-web.sh"
publish = "dist"

# Branch deploys
[context.branch-deploy]
command = "./build-web.sh"
publish = "dist"

# SPA fallback for routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
