name: "Setup Build Environment"
description: "Install system dependencies and Rust toolchain with caching for Bevy builds"

inputs:
  rust-components:
    description: "Additional Rust components to install (e.g., 'rustfmt,clippy')"
    required: false
    default: ""
  rust-targets:
    description: "Additional Rust targets to install (e.g., 'wasm32-unknown-unknown')"
    required: false
    default: ""
  cache-key-suffix:
    description: "Suffix for cache key to differentiate between jobs"
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          libudev-dev \
          libxkbcommon-dev \
          libwayland-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libgl1-mesa-dev \
          pkg-config

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-cargo-

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}
        targets: ${{ inputs.rust-targets }}
